### ISSUE TITLE
Ошибка в описании домашнего задания

### ISSUE THREAD

**Issue by lapssh** [netology-code/py-homework-basic#1]
На странице с [домашним заданием к лекции 2.3](https://github.com/netology-code/py-homework-basic/tree/master/2.3.exceptions)

`Задача №3
Расширить домашние задание из лекции 1.4 «Функции — использование встроенных и создание собственных» новой функцией, выводящей имена всех владельцев документов. С помощью исключения KeyError проверяйте, есть ли поле "name" у документа.`

На самом деле имеется ввиду [лекция 2.1](https://github.com/netology-code/py-homework-basic/tree/master/2.1.functions)
В лекции 1.4 мы парсили csv файл.

**Comment by eshmargunov** [comment]
Спасибо. Исправил
